"""Unify fleet models and add Route model

Revision ID: 930dac054a7a
Revises: 633bc92c8e96
Create Date: 2026-09-11 12:35:29.960746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930dac054a7a'
down_revision = '633bc92c8e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(length=120), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('fleet_maintenance')
    op.drop_table('route')
    op.drop_table('fleet_vehicle')
    op.drop_table('driver')
    with op.batch_alter_table('fleet_maintenances', schema=None) as batch_op:
        batch_op.alter_column('maintenance_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_maintenances', schema=None) as batch_op:
        batch_op.alter_column('maintenance_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    op.create_table('driver',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=14), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('license_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('license_category', sa.VARCHAR(length=5), nullable=False),
    sa.Column('license_expiry', sa.DATE(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('vehicle_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet_vehicle.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('license_number')
    )
    op.create_table('fleet_vehicle',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('plate', sa.VARCHAR(length=10), nullable=False),
    sa.Column('vehicle_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('brand', sa.VARCHAR(length=50), nullable=True),
    sa.Column('model', sa.VARCHAR(length=50), nullable=True),
    sa.Column('manufacture_year', sa.INTEGER(), nullable=True),
    sa.Column('capacity_kg', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('current_mileage', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate')
    )
    op.create_table('route',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('route_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('vehicle_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('driver_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet_vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fleet_maintenance',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('vehicle_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('maintenance_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('workshop', sa.VARCHAR(length=100), nullable=True),
    sa.Column('opened_at', sa.DATETIME(), nullable=True),
    sa.Column('scheduled_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('mileage', sa.INTEGER(), nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('next_maintenance_at', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['fleet_vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('routes')
    # ### end Alembic commands ###
