"""add minimum stock to products

Revision ID: b1544b2eef9b
Revises: 2ad2d53614cb
Create Date: 2026-08-22 10:35:15.291900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1544b2eef9b'
down_revision = '2ad2d53614cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(
    sa.Column(
        "minimum_stock",
        sa.Integer(),
        nullable=False,
        server_default="0"
    )
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('minimum_stock')

    # ### end Alembic commands ###
